FROM nginx:alpine
# COPY frontend/ /usr/share/nginx/html/
COPY  index.html /usr/share/nginx/html/index.html
COPY  admin.html /usr/share/nginx/html/admin.html

COPY  ualflix_logotipo3.png /usr/share/nginx/html/ualflix_logotipo3.png