apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: user-service
  name: user-service
spec:
  ports:
  - name: 6000-6000
    port: 6000
    protocol: TCP
    targetPort: 6000
  selector:
    app: user-service
  type: ClusterIP
status:
  loadBalancer: {}
